language: node_js

node_js:
  - "0.10"

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -q
- sudo apt-get install -y libstdc++6

install:
- npm install --verbose

before_script:
- true

script:
- npm test

